LIST	    P=16F887
#include    "p16F887.inc"

    
W_TEMP	    EQU	    0x20
STATUS_TEMP EQU	    0x21

	    ORG	    0x00
	    GOTO    INICIO
	    ORG	    0x04
	    GOTO    INICIO_ISR
	    ORG	    0x05
INICIO	BANKSEL	ANSELH
	CLRF	ANSELH
	BANKSEL	TRISB
	MOVLW	b'00000110'
	MOVWF	TRISB
	BSF	INTCON,RBIE
	BSF	OPTION_REG,NOT_RBPU
	BSF	INTCON,GIE
	
	

