;*** Directivas de Inclusión ***    
LIST P=16F887                
#include "p16f887.inc"

;**** Configuración General ****    
__CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF    
    
    
W_TEMP		    EQU	0x20
STATUS_TEMP	    EQU 0x21
LED_RING_COUNTER    EQU	0x22
PORT3_MASK	    EQU	0x23
ORG	0x00    
GOTO	INICIO
ORG	0x04
GOTO	INICIO_ISR
ORG	0x05

INICIO	BANKSEL	ANSELH
	CLRF	ANSELH
	BSF	TRISB,TRISB0
	BCF	OPTION_REG,INTEDC
	BSF	OPTION_REG,NOT_RGPU
	CLRF	LED_RING_COUNTER
	BSF	INTCON,INTE
	BSF	INTCON,GIE
	
	LOOP	GOTO	LOOP

INICIO_ISR  MOVWF   W_TEMP
	    SWAP    STATUS,W
	    MOVWF   STATUS_TEMP
	    INCF    LED_RING_COUNTER,F
	    MOVF    LED_RING_COUNTER,W
	    XORLW   0x03
	    BTFSC   STATUS,Z
	    CLRF    LED_RING_COUNTER
	    BCF	    PORTB,RB1
	    BCF	    PORTB,RB2
	    BCF	    PORTB,RB3
	    
	    MOVF    LED_RING_COUNTER,W
	    CALL    TABLE_LEDS
	    MOVWF   PORTB_MASK
	    IORWF   PORTB,F
FIN_ISR	    
	    BCF	    INTCON,INTF
	    SWAPF   STATUS_TEMP,W
	    MOVWF   STATUS
	    SWAPF   W_TEMP,F
	    SWAPF   W_TEMP,W
	    RETFIE
	    